export const sidebarLinks = [
    {
      imgURL: "/icons/home.svg",
      route: "/",
      label: "Home",
    },
    {
      imgURL: "/icons/discover.svg",
      route: "/discover",
      label: "Discover",
    },
    {
      imgURL: "/icons/microphone.svg",
      route: "/create-podcast",
      label: "Create Podcast",
    },
  ];
  
  export const languageOptions = [
    { code: "ar-eg", name: "Arabic (Egypt)" },
    { code: "ar-sa", name: "Arabic (Saudi Arabia)" },
    { code: "bg-bg", name: "Bulgarian" },
    { code: "ca-es", name: "Catalan" },
    { code: "zh-cn", name: "Chinese (China)" },
    { code: "zh-hk", name: "Chinese (Hong Kong)" },
    { code: "zh-tw", name: "Chinese (Taiwan)" },
    { code: "hr-hr", name: "Croatian" },
    { code: "cs-cz", name: "Czech" },
    { code: "da-dk", name: "Danish" },
    { code: "nl-be", name: "Dutch (Belgium)" },
    { code: "nl-nl", name: "Dutch (Netherlands)" },
    { code: "en-au", name: "English (Australia)" },
    { code: "en-ca", name: "English (Canada)" },
    { code: "en-gb", name: "English (Great Britain)" },
    { code: "en-in", name: "English (India)" },
    { code: "en-ie", name: "English (Ireland)" },
    { code: "en-us", name: "English (United States)" },
    { code: "fi-fi", name: "Finnish" },
    { code: "fr-ca", name: "French (Canada)" },
    { code: "fr-fr", name: "French (France)" },
    { code: "fr-ch", name: "French (Switzerland)" },
    { code: "de-at", name: "German (Austria)" },
    { code: "de-de", name: "German (Germany)" },
    { code: "de-ch", name: "German (Switzerland)" },
    { code: "el-gr", name: "Greek" },
    { code: "he-il", name: "Hebrew" },
    { code: "hi-in", name: "Hindi" },
    { code: "hu-hu", name: "Hungarian" },
    { code: "id-id", name: "Indonesian" },
    { code: "it-it", name: "Italian" },
    { code: "ja-jp", name: "Japanese" },
    { code: "ko-kr", name: "Korean" },
    { code: "ms-my", name: "Malay" },
    { code: "nb-no", name: "Norwegian" },
    { code: "pl-pl", name: "Polish" },
    { code: "pt-br", name: "Portuguese (Brazil)" },
    { code: "pt-pt", name: "Portuguese (Portugal)" },
    { code: "ro-ro", name: "Romanian" },
    { code: "ru-ru", name: "Russian" },
    { code: "sk-sk", name: "Slovak" },
    { code: "sl-si", name: "Slovenian" },
    { code: "es-mx", name: "Spanish (Mexico)" },
    { code: "es-es", name: "Spanish (Spain)" },
    { code: "sv-se", name: "Swedish" },
    { code: "ta-in", name: "Tamil" },
    { code: "th-th", name: "Thai" },
    { code: "tr-tr", name: "Turkish" },
    { code: "vi-vn", name: "Vietnamese" },
  ];
 export const podcastData = [
    {
      id: 1,
      title: "The Joe Rogan Experience",
      description: "A long form, in-depth conversation",
      imgURL: "https://picsum.photos/id/1011/200/300",
    },
    {
      id: 2,
      title: "The Futur",
      description: "This is how the news should sound",
      imgURL: "https://picsum.photos/id/1012/200/300",
    },
    {
      id: 3,
      title: "Waveform",
      description: "Join Michelle Obama in conversation",
      imgURL: "https://picsum.photos/id/1013/200/300",
    },
    {
      id: 4,
      title: "The Tech Talks Daily Podcast",
      description: "This is how the news should sound",
      imgURL: "https://picsum.photos/id/1014/200/300",
    },
    {
      id: 5,
      title: "GaryVee Audio Experience",
      description: "A long form, in-depth conversation",
      imgURL: "https://picsum.photos/id/1015/200/300",
    },
    {
      id: 6,
      title: "Syntax",
      description: "Join Michelle Obama in conversation",
      imgURL: "https://picsum.photos/id/1016/200/300",
    },
    {
      id: 7,
      title: "IMPAULSIVE",
      description: "A long form, in-depth conversation",
      imgURL: "https://picsum.photos/id/1019/200/300",
    },
    {
      id: 8,
      title: "Ted Tech",
      description: "This is how the news should sound",
      imgURL: "https://picsum.photos/id/1018/200/300",
    },
];

  